<?php use Phalcon\Tag as Tag ?>

<?= $this->getContent() ?>

<?= Tag::form(array('users/login', 'class' => 'login-form', 'autocomplete' => 'off')) ?>

	<p>
		<label for="login">Имя</label>
		<input type="text" id="login" class="input" name="login" size="30">
	</p>

	<p>
		<label for="password">Пароль</label>
		<input type="password" id="password" class="input" name="password" size="30">
	</p>

	<p>
		<?= Tag::submitButton(array('Вход', 'class' => 'btn btn-half')) ?><a href="/" class="btn btn-gray btn-half">Отмена</a>
	</p>

<?= Tag::tagHtmlClose('form') ?>