<?php use Phalcon\Tag as Tag; ?>

<article class="post post-<?= $post->type ?>" id="post-<?= $post->id ?>" itemscope="" itemtype="http://schema.org/BlogPosting">
	<h2  class="post-title" itemprop="name"><?=
		Tag::linkTo([
			$this->url->get([ 'for' => 'post-link', 'slug' => $post->slug ]),
			$post->subject,
			'itemprop' => 'url'
		])
	?></h2>
	<div class="post-item"><?= $post->getDate() ?></div>
	<div class="post-text"  itemprop="articleBody"><?= $post->getContent('short') ?></div>
	<?php
		if ($post->full_text)
			echo Tag::linkTo([
				$this->url->get([ 'for' => 'post-link', 'slug' => $post->slug ]).'#readmore',
				'Читать далее <i class="fa fa-angle-right"></i>',
				'class' => 'readmore'
			])
	?>

	<?php if ($this->session->has('auth_login'))
		$this->partial("partial/dropdown"); ?>
</article>