<?php use Phalcon\Tag as Tag; ?>

<?= $this->getContent() ?>

<div class="share">
	<div class="share-text">Поделиться:</div>
	<div class="share-block">			
		<a title="Поделиться в ВКонтакте" id="vk">VK</a>
		<a title="Поделиться в Фейсбуке" id="fb">Facebook</a>
		<a title="Поделиться в Твиттере" id="tw">Twitter</a>
		<a title="Поделиться в Тамблере" id="tm">Tumblr</a>
		<a title="Поделиться по почте" id="po">E-Mail</a>
	</div>
</div>