<?php use \Phalcon\Tag as Tag; ?>

<?= $this->getContent(); ?>

<script type="text/javascript">
	$(document).ready(function() {
		$('#text').redactor({
			buttonSource: true,
			plugins: ['video', 'readmore']
		});
	});
</script>

<?= Tag::form(array("post/create", "class" => "form addpost-form")) ?>
	<p>
		<label for="subject">Тема</label>
		<input type="text" name="post_subject" id="subject" placeholder="Заголовок записи" class="input">
	</p>
	<p>
		<label for="slug">Алиас</label>
		<input type="text" name="post_slug" id="slug" placeholder="Алиас" class="input">
	</p>
	<p>
		<label for="text">Сообщение</label>
		<textarea name="post_text" cols="40" id="text" rows="10" placeholder="Текст"></textarea>
	</p>

	<?= Tag::submitButton(array('Добавить пост', 'name' => 'post_add', 'class' => 'btn')) ?>
	<?= Tag::submitButton(array('Черновик', 'name' => 'post_draft', 'class' => 'btn btn-gray')) ?>
	<a href="/" class="btn btn-cancle">Отмена</a>

	<hr>

<?= Tag::tagHtmlClose("form") ?>