<?php use \Phalcon\Tag as Tag; ?>

<?= $this->getContent(); ?>

<?= Tag::form(array("post/create", "class" => "box-form")) ?>
	<p class="form-panel">
		<input type="text" name="post_subject" class="subject" placeholder="Тема"> <input type="submit" value="Добавить пост">
	</p>
	
	<textarea name="post_message" cols="40" id="message" rows="10" placeholder="Текст"></textarea>

	<p class="form-panel">
		Категории: <?= Tag::select(array(
			"post_category", "class" => "select",
			Categories::find('id'),
			"using" => array("abbr", "name"),
			"useEmpty" => true,
			'emptyText' => 'Без категории'
		));
		?>
		Комментарии: <?= Tag::selectStatic(array(
	        "post_comments", "class" => "select",
	        array(
	            "1" => "Включить",
	            "0" => "Выключить",
	        )
	    ));
	    ?>
	</p>

<?= Tag::tagHtmlClose("form") ?>
