<?php use \Phalcon\Tag as Tag; ?>

<?= $this->getContent(); ?>

<script type="text/javascript">
	$(document).ready(function() {
		$('#message').redactor({
			buttonSource: true,
			plugins: ['video']
		});
	});
</script>

<?= Tag::form(array("post/update", "class" => "addpost-form")) ?>

	<input type="hidden" name="post_id" value="<?= $post->id; ?>">

	<input type="text" name="post_subject" id="subject" placeholder="Заголовок записи" value="<?= $post->subject; ?>">

	<input type="text" name="post_slug" id="slug" placeholder="Алиас" value="<?= $post->slug; ?>">

	<textarea name="post_message" cols="40" id="message" rows="10" placeholder="Текст"><?= $post->message; ?></textarea>

	<?= Tag::submitButton(array('Сохранить пост', 'class' => 'btn btn-half')) ?><a href="/" class="btn btn-gray btn-half">Отмена</a>

<?= Tag::tagHtmlClose("form") ?>