<?php use \Phalcon\Tag as Tag; ?>

<script type="text/javascript">
	$(document).ready(function() {
		$('#text').redactor({
			buttonSource: true,
			imageUpload: "<?= $this->url->get([ 'for' => 'post-upload' ]) ?>",
			plugins: ['video', 'readmore']
		});
	});
</script>

<?= Tag::form([ $this->url->get([ 'for' => 'post-update', 'slug' => $post->slug ]), 'class' => 'form addpost-form' ]) ?>
	<div class="form-control">
		<label class="form-label" for="subject">Заголовок записи</label>
		<span class="form-help">Не больше 300 символов</span>
		<input type="text" name="post_subject" id="subject" placeholder="Заголовок записи" class="input" value="<?= $post->subject; ?>">
	</div>
	
	<div class="form-control">
		<label class="form-label" for="slug">Алиас</label>
		<span class="form-help">Должен быть уникален</span>
		<input type="text" name="post_slug" id="slug" placeholder="Алиас" class="input" value="<?= $post->slug; ?>">
	</div>
	
	<div class="form-control">
		<label class="form-label" for="text">Сообщение</label>
		<span class="form-help">Пиши нормально, блин!</span>
		<textarea name="post_text" cols="40" id="text" rows="10" placeholder="Сообщение"><?= $post->getContent('full') ?></textarea>
	</div>

	<div class="form-control">
		<label class="form-label" for="is_comment">Комментарии</label>
		<select name="post_is_comment" id="is_comment">
			<option value="true">Включены</option>
			<option value="false">Выключены</option>
		</select>
	</div>

	<hr>

	<div class="form-control">
		<label class="form-label" for="meta_description">Описание</label>
		<input type="text" name="post_meta_description" id="meta_description" placeholder="Обычно это текст до красной строки" class="input" value="<?= $post->meta_description; ?>">
	</div>

	<div class="form-control">
		<label class="form-label" for="meta_keywords">Ключевые слова</label>
		<input type="text" name="post_meta_keywords" id="meta_keywords" placeholder="утка, нос, котопёс, веб, пушок, горшок" class="input" value="<?= $post->meta_keywords; ?>">
	</div>

	<hr>

	<div class="form-control">
		<?= Tag::submitButton([ 'Сохранить пост', 'name' => 'post_add', 'class' => 'btn' ]) ?>
		<?= Tag::submitButton([ 'Сохранить черновик', 'name' => 'post_draft', 'class' => 'btn btn-gray' ]) ?>
		<?= Tag::linkTo([
				$this->url->get([ 'for' => 'home-link' ]),
				'Отмена',
				'class' => 'btn btn-cancle'
			])
		?>
		<?= Tag::linkTo([
				$this->url->get([ 'for' => 'post-delete', 'slug' => $post->slug ]),
				'Удалить',
				'class' => 'btn btn-remove right'
			]);
		?>
	</div>

<?= Tag::endForm() ?>