<?php use Phalcon\Tag as Tag; ?>

<?= $this->getContent() ?>

<?php
	foreach ($posts->items as $post)
		$this->partial("partial/post", array('post' => $post, 'type' => 'short'))
?>


<?php if ($posts->first != $posts->total_pages) { ?>

<article class="paginator">
	<?php if ($posts->current != $posts->first) { ?>
		<a class="paginator-item left" href="?page=<?= $posts->before; ?>" rel="prev"><i class="fa fa-angle-double-left"></i> Предыдущая</a>
	<?php } ?>

	<?php if ($posts->current != $posts->last) { ?>
		<a class="paginator-item right" href="?page=<?= $posts->next; ?>" rel="next">Следующая <i class="fa fa-angle-double-right"></i></a>
	<?php } ?>
</article>

<?php } ?>