<?php use Phalcon\Tag as Tag; ?>

<?php
	foreach ($posts->items as $post)
		$this->partial("partial/post")
?>


<?php if ($posts->first != $posts->total_pages) { ?>

<div class="paginator">
<?php
	if ($posts->current != $posts->first)
		echo Tag::linkTo([
			'?page='.$posts->before,
			'<i class="fa fa-angle-double-left"></i> Предыдущая',
			'class' => 'paginator-item left',
			'rel' => 'prev'
		]);


	if ($posts->current != $posts->last)
		echo Tag::linkTo([
			'?page='.$posts->next,
			'Следующая <i class="fa fa-angle-double-right"></i>',
			'class' => 'paginator-item right',
			'rel' => 'next'
		]);
?>
</div>

<?php } ?>