<?php use Phalcon\Tag as Tag; ?>

<?= $this->getContent() ?>

<?php $this->partial("partial/full_post", array('post' => $post)) ?>
<hr>
<?php $this->partial("partial/share") ?>
<hr>
<div class="comments">
	<div id="disqus_thread"></div>
	<script type="text/javascript">
		var disqus_identifier = '<?= $post->id; ?>';
		var disqus_shortname = 'ТВОЙ_ДИСКУС_АЙДИ';
		(function() {
			var dsq = document.createElement('script');
			dsq.type = 'text/javascript';
			dsq.async = true;
			dsq.src = '//'+disqus_shortname+'.disqus.com/embed.js';
			(document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
		})();
	</script>	
</div>