<?php use Phalcon\Tag as Tag; ?>

<?= $this->getContent() ?>

<article class="box-thread" id="box<?= $post->id ?>">
	<h2><?= Tag::linkTo('post/show/'.$post->id, $post->subject) ?></h2>
	<div class="thread-time"><?= $post->timestamp ?></div>
	<div class="thread-text"><?= $post->message ?></div>
	<? if($post->category || $post->comments_enabled) { ?>
	<div class="thread-info">
		<? if($post->category) { ?>
			<span class="thread-info-category">Категория: <?= Tag::linkTo('post/category/'.$post->category, $post->categories->name) ?></span>
		<? } ?>
		<? if($post->comments_enabled) { ?>
			<span class="thread-info-comments"><?= Tag::linkTo('post/show/'.$post->id. '#comments', 'Комментариев: ' .$post->count) ?></span>
		<? } ?>
	</div>
	<? } ?>
</article>
<hr>

<? if ($post->comments_enabled) { ?>
<section class="box-comments" id="comments">
	<h4 class="title">Комментарии:</h4>
	<hr>

	<?php foreach ($comments as $comment){ ?>
	<div class="box-post" id="reply_<?= $comment->id ?>">
		<a id="<?= $comment->id ?>"></a>
		<p class="post-info">
			<span class="name"><?= $comment->name ?><b><?= $comment->tripcode ?></b></span>
			<span class="time"><?= $comment->timestamp ?></span>
			<a href="#<?= $comment->id ?>" onclick="insert('>><?= $comment->id ?>'); return false;">#<?= $comment->id ?></a>
		</p>
		<p class="post-text"><?= $comment->message ?></p>
	</div>
	<hr>
	<?php } ?>

	<?= Tag::form(array("comments/add", "method" => "post", "name" => "formpost", "class" => "box-form", "id" => "form"));?>

		<?= Tag::hiddenField(array('post', 'value' => $post->id)) ?>
		<?= Tag::hiddenField(array($this->security->getTokenKey(), 'value' => $this->security->getToken())) ?>

		<p class="form-name">
			<?= Tag::textField(array('comments_name', 'maxlength' => 15, 'placeholder' => 'Имя#Код')) ?>
			<?= Tag::submitButton('Добавить пост'); ?>
			<?= Tag::linkTo(array('pages/markup', 'Правила разметки', 'class' => 'form-markup')) ?>
		</p>				
		<p class="form-message">
			<textarea name="comments_message" id="message" cols="55" rows="5" placeholder="Твой текст"></textarea>
		</p>
		<p class="form-captcha">			
			<?= Tag::image(array('captcha.php', 'id' => 'captchaimg', 'alt' => 'Проверочный код'));?>
			<?= Tag::textField(array('comments_captcha', 'maxlength' => 4)) ?>
		</p>
	<?= Tag::tagHtmlClose('form')?>

</section>
<hr>
<b><?= Tag::linkTo('post', 'Назад') ?></b>

<? } else { ?>
<section class="box-message error">Комментарии отключены</section>
<? } ?>