
<?php echo \Phalcon\Tag::form(array("categories/create", "autocomplete" => "off")) ?>

    <table width="100%">
        <tr>
            <td align="left"><?php echo \Phalcon\Tag::linkTo(array("categories", "Go Back", "class" => "btn")) ?></td>
            <td align="right"><?php echo \Phalcon\Tag::submitButton(array("Save", "class" => "btn")) ?></td>
        <tr>
    </table>

    <?php echo $this->getContent(); ?>

    <div align="center">
        <h1>Create categories</h1>
    </div>

    <table align="center">
        <tr>
            <td align="right">
                <label for="name">Название</label>
            </td>
            <td align="left">
                <?php echo \Phalcon\Tag::textField(array("name", "size" => 30)) ?>
            </td>
        </tr>
        <tr>
            <td align="right">
                <label for="abbr">Аббревиатура</label>
            </td>
            <td align="left">
                <?php echo \Phalcon\Tag::textField(array("abbr", "size" => 30)) ?>
            </td>
        </tr>
    </table>
</form>
