<?php use Phalcon\Tag as Tag ?>
<?= Tag::getDocType(); ?>
<html lang="ru">
<head>
	<meta charset="utf-8">
	<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
	<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
	<meta name="HandheldFriendly" content="true">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">

	<?= $this->tag->getTitle(); ?>
	<?= $this->tag->getDescription(); ?>
	<?= $this->tag->getKeywords(); ?>

	<?= $this->assets->outputCss(); ?>
	<?= $this->assets->outputJs(); ?>

</head>
<body>

<header id="header">
<div class="warp">

	<div class="header-name">
		<a href="/"><?= Tag::getValue('name'); ?></a>
	</div>
	<ul class="header-button">
	<?php if ($this->session->has('auth_login')) { ?>
		<li><a id="add" href="/p/create"><i class="fa fa-pencil"></i></a></li>
	<?php } ?>
		<li><a id="bars" href="#"><i class="fa fa-bars"></i></a></li>
	<?php if ($this->session->has('auth_login')) { ?>
		<li><a href="/users/logout"><i class="fa fa-sign-out"></i></a></li>
	<?php } ?>
	</ul>
	<div class="header-menu" role="navigation">
		<ul>
			<li><?= Tag::linkTo('about', 'Обо мне'); ?></li>
			<li><?= Tag::linkTo('snake', 'Змейка'); ?></li>
		</ul>
	</div>

</div>
</header>

<?php $this->flashSession->output(); ?>

<section>
<div class="warp">

	<?= $this->getContent() ?>

</div>
</section>


<footer id="footer">
<div class="warp">

	<p>Powered by <b>Skopy</b> <a href="#" id="rise"><i class="fa fa-angle-up"></i></a></p>
	
</div>
</footer>

</body>
</html>