<?php use Phalcon\Tag as Tag ?>
<?= Tag::getDocType(); ?>
<html lang="ru">
<head>
	<meta charset="utf-8">
	<link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
	<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
	<meta name="HandheldFriendly" content="true">

	<?= Tag::getTitle(); ?>
	<?= Tag::getValue('description'); ?>
	<?= Tag::getValue('keywords'); ?>

	<?php $this->assets->outputCss() ?>

	<?php $this->assets->outputJs() ?>

</head>
<body>

<header>
	<div class="warp">
	<div class="header-name">
		<a href="/">Иван Иванов</a>
	</div>
	<ul class="header-menu">
		<li><?= Tag::linkTo('post', 'Блог') ?></li>
		<?php if ($this->session->has('auth_login')) { ?>
		<li><?= Tag::linkTo('users/logout', 'Выход') ?></li>
		<?php } ?>
	</ul>
	</div>
	<ul class="header-button">
		<?php if ($this->session->has('auth_login')) { ?>
		<li><a id="add" href="/p/create"><i class="fa fa-pencil"></i></a></li>
		<?php } ?>
		<li><a id="search" href="#"><i class="fa fa-search"></i></a></li>
		<li><a id="bars" href="#"><i class="fa fa-bars"></i></a></li>
	</ul>
</header>

<?php $this->flashSession->output(); ?>

<section id="post">
<div class="warp">

	<?= $this->getContent() ?>

</div>
</section>

<footer>
<div class="warp">

	<p>Powered by <b>Phalcon</b></p>

</div>
</footer>

</body>
</html>